name: Build and build

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
    paths-ignore:
      - "ReadMe.md"
      - ".gitignore"
      - ".editorconfig"
  pull_request:
    branches: [ '*' ]
    paths-ignore:
      - "ReadMe.md"
      - ".gitignore"
      - ".editorconfig"
    tags:        
      - '**' 

permissions:
  contents: write

jobs:
  build:    
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Get current release
      run: echo "CURRENT_RELEASE=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
    - name: Get current commit
      run: echo "CURRENT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build
      env:
        os: ${{ runner.os == 'Windows' && 'win' || runner.os == 'macOS' && 'osx' || 'linux' }}
      run: |
        dotnet publish Celeste64Launcher/Celeste64Launcher.csproj -c Release -r ${{env.os}}-x64 -p:ImportByWildcardBeforeSolution=false "-p:EmbeddedBuildProperty=ModVersion=${{env.CURRENT_COMMIT}}"
    - name: Copy Content
      run: |
        cp -r Content Mods Celeste64Launcher/bin/Release/net8.0/${{runner.os}}-x64/publish
    - name: Create ZIP archives
      run: |
        pushd Celeste64Launcher/bin/Release/net8.0/${{runner.os}}-x64/publish
        zip -r ../../../../../../Celeste64-Fuji-${{env.CURRENT_RELEASE}}${{env.CURRENT_COMMIT}}-${{runner.os,,}}-x64.zip ./*
        popd
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{env.CURRENT_RELEASE}}${{env.CURRENT_COMMIT}}',
            sha: context.sha
          })
    - name: Publish Github Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{env.CURRENT_RELEASE}}${{env.CURRENT_COMMIT}}
        name: Celeste 64 Fuji ${{env.CURRENT_RELEASE}}${{env.CURRENT_COMMIT}}
        body: |
          # Instructions:

          - Download and extract the zip file below according to your computer
          - Run the Celeste64 application from the extracted files

          # Requirements:

          - **Windows:** 10 or later, x64
          - **Linux:** [Distro support list](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md), x64
          - **macOS:** Monterey or later, x64 Intel-based or Apple Silicon with Rosetta
        files: Celeste64-Fuji-*.zip