name: Build and build

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
    paths-ignore:
      - "ReadMe.md"
      - ".gitignore"
      - ".editorconfig"
  pull_request:
    branches: [ '*' ]
    paths-ignore:
      - "ReadMe.md"
      - ".gitignore"
      - ".editorconfig"
    tags:        
      - '**' 

permissions:
  contents: write

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Get current tag
      run: echo "CURRENT_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build Windows x86-64
      run: dotnet publish Celeste64Launcher/Celeste64Launcher.csproj -c Release -r win-x64 "-p:EmbeddedBuildProperty=ModVersion=${{env.CURRENT_TAG}}"
    - name: Build Linux x86-64
      run: dotnet publish Celeste64Launcher/Celeste64Launcher.csproj -c Release -r linux-x64 "-p:EmbeddedBuildProperty=ModVersion=${{env.CURRENT_TAG}}"
    - name: Build macOS x86-64
      run: dotnet publish Celeste64Launcher/Celeste64Launcher.csproj -c Release -r osx-x64 "-p:EmbeddedBuildProperty=ModVersion=${{env.CURRENT_TAG}}"
    - name: Copy Content
      run: |
        cp -r Content Mods Celeste64Launcher/bin/Release/net8.0/win-x64/publish
        cp -r Content Mods Celeste64Launcher/bin/Release/net8.0/linux-x64/publish
        cp -r Content Mods Celeste64Launcher/bin/Release/net8.0/osx-x64/publish
    - name: Create ZIP archives
      run: |
        pushd Celeste64Launcher/bin/Release/net8.0/win-x64/publish
        zip -r ../../../../../../Celeste64-Fuji-${{env.CURRENT_TAG}}-win-x64.zip ./*
        popd
        pushd Celeste64Launcher/bin/Release/net8.0/linux-x64/publish
        zip -r ../../../../../../Celeste64-Fuji-${{env.CURRENT_TAG}}-linux-x64.zip ./*
        popd
        pushd Celeste64Launcher/bin/Release/net8.0/osx-x64/publish
        zip -r ../../../../../../Celeste64-Fuji-${{env.CURRENT_TAG}}-osx-x64.zip ./*
        popd
    - name: Publish Github Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{env.CURRENT_TAG}}
        name: Celeste 64 Fuji ${{env.CURRENT_TAG}}
        body: |
          # Instructions:

          - Download and extract the zip file below according to your computer
          - Run the Celeste64 application from the extracted files

          # Requirements:

          - **Windows:** 10 or later, x64
          - **Linux:** [Distro support list](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md), x64
          - **macOS:** Monterey or later, x64 Intel-based or Apple Silicon with Rosetta
        files: Celeste64-Fuji-*.zip